name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-02-03
      - uses: Swatinem/rust-cache@v2
      - run: pip install -e '.[dev]'
      - run: pytest -s tests
      - run: cargo test --all

  lint_rust:
    name: Lint Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-02-03
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all -- -D warnings

  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install black~=24.0
      - run: black --check python
      - run: black --check tests
